# Generated by Django 5.2.15 on 2026-06-26 14:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_userpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='temp_uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Temporary Upload',
                'verbose_name_plural': 'Temporary Uploads',
            },
        ),
    ]
