# Generated by Django 5.2.17 on 2026-09-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_temporaryupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity',
            field=models.CharField(blank=True, choices=[('restaurant', 'Restaurant or café'), ('guesthouse', 'Guesthouse or hotel'), ('artisan', 'Artisan'), ('shop', 'Shop'), ('wellness', 'Wellness'), ('activities', 'Activities and tours'), ('events', 'Events'), ('other', 'Other')], default='', max_length=32, verbose_name='Activity'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Phone'),
        ),
    ]
