# Generated by Django 5.2.13 on 2026-05-08 15:17

import guard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0055_event_boost'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='voiceover_en',
            field=models.FileField(blank=True, help_text='Upload an audio voiceover in English (AAC format only)', null=True, upload_to=guard.models.location_voiceover_path, verbose_name='Voiceover (English)'),
        ),
        migrations.AddField(
            model_name='location',
            name='voiceover_fr',
            field=models.FileField(blank=True, help_text='Upload an audio voiceover in French (AAC format only)', null=True, upload_to=guard.models.location_voiceover_path, verbose_name='Voiceover (French)'),
        ),
    ]
