# Generated by Django 5.2.13 on 2026-05-18 15:01

import django.db.models.deletion
import guard.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0013_alter_city_alternate_names_alter_city_country_and_more'),
        ('guard', '0056_location_voiceover_en_location_voiceover_fr'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('icon', models.CharField(blank=True, help_text='SF Symbol name (iOS) / Material icon name (Android)', max_length=100, null=True, verbose_name='Icon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Merchant Category',
                'verbose_name_plural': 'Merchant Categories',
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', tinymce.models.HTMLField(verbose_name='Description')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('price_range', models.CharField(choices=[('€', '€ — Budget friendly'), ('€€', '€€ — Moderate'), ('€€€', '€€€ — Premium')], default='€€', max_length=5, verbose_name='Price Range')),
                ('open_from', models.TimeField(blank=True, null=True, verbose_name='Open From')),
                ('open_to', models.TimeField(blank=True, null=True, verbose_name='Open To')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=guard.models.merchant_cover_path, verbose_name='Cover Image')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured merchants appear at the top of the list', verbose_name='Featured')),
                ('contract_status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Contract Status')),
                ('contract_start', models.DateField(blank=True, null=True, verbose_name='Contract Start')),
                ('contract_end', models.DateField(blank=True, null=True, verbose_name='Contract End')),
                ('contract_notes', models.TextField(blank=True, help_text="Internal notes about this merchant's contract", null=True, verbose_name='Contract Notes')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchants', to='cities_light.city', verbose_name='City')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchants', to='guard.merchantcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Merchant',
                'verbose_name_plural': 'Merchants',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MerchantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('image_mobile', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='guard.merchant', verbose_name='Merchant')),
            ],
            options={
                'verbose_name': 'Merchant Image',
                'verbose_name_plural': 'Merchant Images',
            },
        ),
        migrations.CreateModel(
            name='MerchantProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('image', models.ImageField(blank=True, null=True, upload_to=guard.models.merchant_product_image_path, verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='guard.merchant', verbose_name='Merchant')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='MerchantRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5', verbose_name='Stars')),
                ('reviewer_name', models.CharField(max_length=150, verbose_name='Name')),
                ('reviewer_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Stored for spam protection', null=True, verbose_name='IP Address')),
                ('is_approved', models.BooleanField(default=False, help_text='Only approved ratings are shown in the app', verbose_name='Approved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='guard.merchant', verbose_name='Merchant')),
            ],
            options={
                'verbose_name': 'Merchant Rating',
                'verbose_name_plural': 'Merchant Ratings',
                'ordering': ['-created_at'],
                'unique_together': {('merchant', 'reviewer_email')},
            },
        ),
    ]
