# Generated by Django 5.2.13 on 2026-05-18 15:04

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0057_merchantcategory_merchant_merchantimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='address_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='address_fr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='description_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='description_fr',
            field=tinymce.models.HTMLField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='merchantcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='merchantcategory',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='merchantproduct',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Product Name'),
        ),
        migrations.AddField(
            model_name='merchantproduct',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Product Name'),
        ),
    ]
