# Generated by Django 5.2.13 on 2026-05-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0058_merchant_address_en_merchant_address_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='short_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='short_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
