# Generated by Django 5.2.13 on 2026-06-10 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0013_alter_city_alternate_names_alter_city_country_and_more'),
        ('guard', '0060_ad_created_by_ad_updated_by_event_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region_id', models.CharField(help_text="Unique identifier string, e.g., 'sousse_medina'", max_length=100, unique=True, verbose_name='Region ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_fr', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('radius', models.FloatField(help_text='Radius in meters, e.g., 2000', verbose_name='Radius')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_cities', to='cities_light.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Offline City',
                'verbose_name_plural': 'Offline Cities',
            },
        ),
    ]
