# Generated by Django 5.2.15 on 2026-07-01 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0061_offlinecity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='endDate',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='ad',
            name='startDate',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
