# Generated by Django 5.2.15 on 2026-07-01 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guard', '0062_ad_enddate_ad_startdate'),
        ('shared', '0004_temporaryupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('subscription', 'Subscription'), ('event_boost', 'Event Boost'), ('ad_boost', 'Ad Boost')], max_length=32, verbose_name='Transaction Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('rejected', 'Rejected')], default='pending', max_length=32, verbose_name='Status')),
                ('months', models.IntegerField(blank=True, null=True, verbose_name='Subscription Months')),
                ('ad_start_date', models.DateField(blank=True, null=True, verbose_name='Ad Start Date')),
                ('ad_end_date', models.DateField(blank=True, null=True, verbose_name='Ad End Date')),
                ('amount_ht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount HT')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tax Amount (19%)')),
                ('timbre_fiscal', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Timbre Fiscal')),
                ('total_ttc', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total TTC')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validated At')),
                ('ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='guard.ad', verbose_name='Ad')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='guard.event', verbose_name='Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='shared.userprofile', verbose_name='User Profile')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
